### ISSUE TITLE
--start-hidden does not work

### ISSUE THREAD

**Issue by driesmp** [rozhuk-im/gtk-mixer#2]
Hi,

So in my i3 config I have:
`exec --no-startup-id gtk-mixer --start-hidden`

But it still seems to maximize on start-up. Is this the correct flag?

**Comment by rozhuk-im** [comment]
Yes, ```gtk-mixer --start-hidden``` will start app as tray icon only.
This feature added since 1.0.2, make sure that your version is 1.0.2.

**Comment by driesmp** [comment]
Ah yes I see, could you update the FreeBSD port? Feel free to tag me on bugzilla driesm@.

**Comment by rozhuk-im** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260648
